// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThreadPoolGuardian.Data;

#nullable disable

namespace ThreadPoolGuardian.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThreadPoolGuardian.Models.ThreadPoolMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableThreads")
                        .HasColumnType("int");

                    b.Property<int>("MaxThreads")
                        .HasColumnType("int");

                    b.Property<int>("PendingWorkItems")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsedThreads")
                        .HasColumnType("int");

                    b.Property<double>("UtilizationPercent")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Timestamp");

                    b.ToTable("ThreadPoolMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
